# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0005_auto_20170814_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(height_field='300px', upload_to='', verbose_name='Captured image', width_field='300px'),
        ),
    ]
