# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0006_auto_20170814_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(default=300), upload_to='', verbose_name='Captured image', width_field=models.IntegerField(default=300)),
        ),
    ]
