# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0007_auto_20170814_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', verbose_name='Captured image', width_field='width'),
        ),
    ]
