# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0008_auto_20170814_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='height',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='width',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Captured image'),
        ),
    ]
