# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0009_auto_20171107_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureimage',
            name='model_pic',
            field=models.FileField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
