# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0010_auto_20171107_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Captured image'),
        ),
    ]
