# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileNetworks', '0002_auto_20170722_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNetworkOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobileNetworks.MobileNetworks')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mobile network operators',
                'verbose_name': 'Mobile network operator',
            },
        ),
    ]
