# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileNetworks', '0002_auto_20170722_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('mobile_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileNetworks.MobileNetworks')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registered sims',
                'verbose_name': 'Registered sim',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registeredsims',
            unique_together=set([('owner', 'phone_number')]),
        ),
    ]
