# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsims',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
