# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileNetworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenetworks',
            options={'verbose_name': 'Mobile network', 'verbose_name_plural': 'Mobile networks'},
        ),
    ]
